In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeRegressor

In [3]:
df_train = pd.read_csv('train.csv')
df_train.head()

id  age     sex        bmi  children smoker     region  charges
0   0   26    male  32.665465         3     no  southeast        0
1   1   41    male  29.798725         1     no  southwest        0
2   2   28    male  32.722029         0    yes  northwest        1
3   3   20  female  38.429831         2     no  southeast        0
4   4   45  female  29.641854         1     no  northwest        0

In [4]:
df_test = pd.read_csv('test.csv')
df_test.head()

id  age     sex        bmi  children smoker     region
0  13   19    male  24.365178         1     no  northeast
1  23   59    male  33.997763         0    yes  northeast
2  27   42  female  29.283450         0     no  southwest
3  28   30    male  24.903725         1     no  northwest
4  29   41  female  29.644536         0     no  southwest

In [5]:
df_train.isnull().sum()

id          0
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
df_test.isnull().sum()

id          0
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
dtype: int64

In [7]:
train_x = df_train[['age','sex','bmi','children','smoker','region']]
train_t = df_train['charges']

In [8]:
train_x['sex'] = train_x['sex'].replace('male', '0').replace('female','1')
df_test['sex'] = df_test['sex'].replace('male','0').replace('female','1')

<ipython-input-8-e05ad798614c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_x['sex'] = train_x['sex'].replace('male', '0').replace('female','1')


In [9]:
train_x['smoker'] = train_x['smoker'].replace('no', '0').replace('yes','1')
df_test['smoker'] = df_test['smoker'].replace('no','0').replace('yes','1')

<ipython-input-9-1dfdee3c3c61>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_x['smoker'] = train_x['smoker'].replace('no', '0').replace('yes','1')


In [10]:
train_x['region'] = train_x['region'].replace('southeast', '0').replace('southwest','1').replace('northwest','2').replace('northeast','3')
df_test['region'] = df_test['region'].replace('southeast','0').replace('southwest','1').replace('northwest','2').replace('northeast','3')

<ipython-input-10-2a7c18faa9c3>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_x['region'] = train_x['region'].replace('southeast', '0').replace('southwest','1').replace('northwest','2').replace('northeast','3')


In [11]:
#train_t = train_t.replace('0', '低').replace('1','中').replace('2','高')

In [12]:
train_t.unique()

array([0, 1, 2])

In [13]:
test_x = df_test[['age','sex','bmi','children','smoker','region']]

In [14]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(train_x)
x_test_scaled = scaler.fit_transform(test_x)

In [15]:
model = DecisionTreeRegressor(max_depth=5,random_state=0)
model.fit(train_x,train_t)

DecisionTreeRegressor(max_depth=5, random_state=0)

In [16]:
df_test['charges'] = model.predict(x_test_scaled)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


In [17]:
df_test.head()

id  age sex        bmi  children smoker region  charges
0  13   19   0  24.365178         1      0      3      1.0
1  23   59   0  33.997763         0      1      3      0.5
2  27   42   1  29.283450         0      0      1      1.0
3  28   30   0  24.903725         1      0      2      1.0
4  29   41   1  29.644536         0      0      1      1.0

In [18]:
df_test['charges'].unique()

array([1. , 0.5])

In [19]:
submission = df_test[['id','charges']]
submission.to_csv('submission_dtr.csv', index=None, line_terminator='\n',header=False)

<ipython-input-19-1ebcd5a1e8be>:2: FutureWarning: the 'line_terminator'' keyword is deprecated, use 'lineterminator' instead.
  submission.to_csv('submission_dtr.csv', index=None, line_terminator='\n',header=False)


In [20]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(penalty='none')
model.fit(train_x, train_t)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(penalty='none')

In [21]:
df_Logi = df_test
df_Logi['charges'] = model.predict(x_test_scaled)
df_Logi.head()

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


id  age sex        bmi  children smoker region  charges
0  13   19   0  24.365178         1      0      3        0
1  23   59   0  33.997763         0      1      3        2
2  27   42   1  29.283450         0      0      1        0
3  28   30   0  24.903725         1      0      2        0
4  29   41   1  29.644536         0      0      1        0

In [22]:
submission2 = df_Logi[['id','charges']]
submission2.to_csv('submission_log.csv', index=False, line_terminator='\n',header=False)

<ipython-input-22-963c1d66c4ad>:2: FutureWarning: the 'line_terminator'' keyword is deprecated, use 'lineterminator' instead.
  submission2.to_csv('submission_log.csv', index=False, line_terminator='\n',header=False)


In [35]:
from sklearn.svm import SVC
svc = SVC()

svc.fit(train_x,train_t)

SVC()

In [36]:
df_svc = df_test
df_svc.head()

id  age sex        bmi  children smoker region  charges
0  13   19   0  24.365178         1      0      3        0
1  23   59   0  33.997763         0      1      3        0
2  27   42   1  29.283450         0      0      1        0
3  28   30   0  24.903725         1      0      2        0
4  29   41   1  29.644536         0      0      1        0

In [37]:
df_svc['charges'] = svc.predict(x_test_scaled)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [38]:
df_svc.head()

id  age sex        bmi  children smoker region  charges
0  13   19   0  24.365178         1      0      3        0
1  23   59   0  33.997763         0      1      3        0
2  27   42   1  29.283450         0      0      1        0
3  28   30   0  24.903725         1      0      2        0
4  29   41   1  29.644536         0      0      1        0

In [33]:
df_svc['charges'].unique()

array([0])

In [30]:
submission3 = df_test[['id','charges']]
submission3.to_csv('submission_svc.csv', index=None, line_terminator='\n',header=False)

<ipython-input-30-3472d23ae38d>:2: FutureWarning: the 'line_terminator'' keyword is deprecated, use 'lineterminator' instead.
  submission3.to_csv('submission_svc.csv', index=None, line_terminator='\n',header=False)
